# -*- coding: utf-8 -*-
"""
Created on Sun Jan 20 13:19:04 2019

@author: MSI Gaming
"""

"""The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?"""

from math import sqrt

def gen_nth_tri_num(n):
    return sum(range(n))

def num_factors(n):
    num = 2 # 1 and itself
    for i in range(2, int(sqrt(n))):
        if n % i == 0:
            num += 2
    return num

i = 1
flag = True
while flag:
    ans = gen_nth_tri_num(i)
    if num_factors(ans) > 500:
        flag = False
    else:
        i += 1